import '@styles/globals.css'

import Header from '@components/Header/Header'
import Footer from '@components/Footer/Footer'

export const metadata = {
  title: 'Online Store | Warbak',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer/>
        </body>
    </html>
  )
}
